Fix tests

diff --git a/.github/workflows/reusable-unit-tests.yml b/.github/workflows/reusable-unit-tests.yml
--- a/.github/workflows/reusable-unit-tests.yml
+++ b/.github/workflows/reusable-unit-tests.yml
@@ -15,4 +15,14 @@ jobs:
           node-version: 16
 
       - name: Build and test
-        run: npm install && npm run build && npm run test
+        run: npm ci && npm run test
+
+      - name: Check test results
+        run: |
+          # Check the exit code of the test command
+          if [ ${{ steps.build.outcome }} == 'failure' ]; then
+            echo "Tests failed. Please fix the failing tests before merging."
+            exit 1
+          else
+            echo "Tests passed."
+          fi
